from __future__ import annotations

import json
import os
import sqlite3
from dataclasses import replace
from pathlib import Path
import tempfile
import time
import unittest
from unittest import mock

from gateway import chain, chain_v10, provider_jury, provider_jury_chain
from gateway.identity import create_identity
from gateway.provider_jury_chain import (
    JURY_ASSIGNED_TOPIC,
    JURY_FAILED_TOPIC,
    JURY_REQUESTED_TOPIC,
    JURY_UNAVAILABLE_TOPIC,
    DISPUTE_VOTE_TOPIC,
    DISPUTE_RESOLVED_TOPIC,
    JuryTransactionOutbox,
    ProviderJuryChainAdapter,
    ProviderJuryChainConfig,
    ProviderJuryChainError,
    ProviderJuryDefinitelyNotSentError,
    TRANSACTION_SCHEMA,
    ZERO_BYTES32,
    _array_encoding,
    _word_address,
    _word_hash,
    _word_uint,
    assignment_hash,
)
from gateway.relay_incidents import evidence_hash
from tests.test_chain_v9 import address, digest, key, signer


def topic_address(value: str) -> str:
    return "0x" + "00" * 12 + value[2:]


class ProviderJuryChainTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.contract = address(50)
        self.registry = address(51)
        self.governance = address(52)
        self.reputation_authority = address(53)
        self.penalty = address(54)
        self.sender = signer(90)
        self.config = ProviderJuryChainConfig(
            network_id="fixture",
            rpc_urls=("https://rpc-a.invalid", "https://rpc-b.invalid"),
            chain_id=31337,
            genesis_hash=digest(100), settlement_contract=self.contract,
            settlement_runtime_code_hash=digest(101), jury_registry=self.registry,
            registry_runtime_code_hash=digest(102),
            jury_registry_governance=self.governance,
            reputation_authority=self.reputation_authority,
            bond_penalty_recipient=self.penalty, minimum_reputation=80,
            jury_size=3, adjudication_threshold=2, selection_delay_blocks=2,
            confirmations=2, max_snapshot_age_seconds=300,
        )

    def adapter(self, *, resolver=lambda _snapshot: {}, name="chain.sqlite3", **options):
        if "rpc" in options:
            options.setdefault("allow_test_rpc_override", True)
        return ProviderJuryChainAdapter(
            self.config, outbox_path=Path(self.temporary.name) / name,
            resolve_provider=resolver, sender=self.sender, **options,
        )

    def action_fixture(
        self, *, action="vote_dispute_by_sig", target=None, calldata="0x1234",
        settlement_key=None, **extra,
    ):
        body = {
            "schema": TRANSACTION_SCHEMA, "action": action,
            "network_id": "fixture", "chain_id": 31337,
            "genesis_hash": digest(100), "sender": self.sender,
            "target": target or self.contract, "value": 0,
            "calldata": calldata, "settlement_key": settlement_key or digest(7),
            **extra,
        }
        return {**body, "action_hash": evidence_hash(body)}

    def signed_raw(
        self, action, *, nonce, gas_price_wei=1, gas_units=100_000,
        key_number=90, chain_id=None, target=None, value=0, calldata=None,
    ):
        return chain.sign_legacy_transaction(
            chain.parse_private_key(key(key_number)), nonce, gas_price_wei,
            gas_units, target or action["target"], value,
            bytes.fromhex((calldata or action["calldata"])[2:]),
            chain_id or action["chain_id"],
        )

    def test_assignment_hash_matches_solidity_abi_reference_vector(self) -> None:
        result = assignment_hash(
            registry=address(51), chain_id=31337, settlement=address(50),
            case_id=digest(7), roster_version=9, seed=digest(8),
            minimum_reputation=80, jury_size=3, threshold=2,
            owners=[address(100 + index) for index in range(3)],
            vote_signers=[address(200 + index) for index in range(3)],
            operator_id_hashes=[digest(300 + index) for index in range(3)],
            peer_id_hashes=[digest(400 + index) for index in range(3)],
            capability_hashes=[digest(500 + index) for index in range(3)],
            reputations=[90 + index for index in range(3)],
        )
        # Independently generated by Solidity 0.8.28 using the Registry's exact
        # keccak256(abi.encode(...)) expression.
        self.assertEqual(
            result,
            "0xbd23d59dd90dc84e4e9a38519c04f1e3a8c5ea72a8d5282871be60055bb3eaec",
        )

    def test_chain_config_requires_multi_https_distinct_host_rpc_quorum(self) -> None:
        invalid = (
            ("https://rpc-a.invalid",),
            ("http://rpc-a.invalid", "https://rpc-b.invalid"),
            ("https://user:secret@rpc-a.invalid", "https://rpc-b.invalid"),
            ("https://rpc-a.invalid?token=x", "https://rpc-b.invalid"),
            ("https://rpc-a.invalid#fragment", "https://rpc-b.invalid"),
            (" https://rpc-a.invalid", "https://rpc-b.invalid"),
            ("https://localhost", "https://rpc-b.invalid"),
            ("https://rpc-a.invalid/one", "https://RPC-A.invalid:443/two"),
        )
        for endpoints in invalid:
            with self.subTest(endpoints=endpoints):
                with self.assertRaises(ProviderJuryChainError):
                    replace(self.config, rpc_urls=endpoints)

        with self.assertRaisesRegex(ProviderJuryChainError, "test-only opt-in"):
            ProviderJuryChainAdapter(
                self.config,
                outbox_path=Path(self.temporary.name) / "implicit-rpc.sqlite3",
                resolve_provider=lambda _snapshot: {}, sender=self.sender,
                rpc=lambda _method, _params: None,
            )

    def test_rpc_quorum_all_agrees_and_uses_conservative_quantities(self) -> None:
        adapter = self.adapter(name="rpc-quorum.sqlite3")
        self.addCleanup(adapter.close)
        first, second = self.config.rpc_urls
        responses = {
            "eth_chainId": {first: "0x7a69", second: "0x7a69"},
            "eth_gasPrice": {first: "0x5", second: "0x7"},
            "eth_estimateGas": {first: "0x5208", second: "0x6000"},
            "eth_getBalance": {first: "0x9", second: "0x7"},
            "eth_blockNumber": {first: "0x65", second: "0x64"},
            "eth_sendRawTransaction": {first: digest(9), second: digest(9)},
        }

        def rpc(endpoint, method, _params, _timeout):
            value = responses[method][endpoint]
            if isinstance(value, BaseException):
                raise value
            return value

        with mock.patch.object(provider_jury_chain.chain, "rpc_call", side_effect=rpc):
            self.assertEqual(adapter._rpc("eth_chainId", []), "0x7a69")
            self.assertEqual(adapter._rpc("eth_gasPrice", []), "0x7")
            self.assertEqual(adapter._rpc("eth_estimateGas", []), "0x6000")
            self.assertEqual(adapter._rpc("eth_getBalance", []), "0x7")
            self.assertEqual(adapter._rpc("eth_blockNumber", []), "0x64")
            self.assertEqual(
                adapter._rpc("eth_sendRawTransaction", ["0x01"]), digest(9),
            )

            responses["eth_chainId"][second] = "0x1"
            with self.assertRaisesRegex(ProviderJuryChainError, "disagree"):
                adapter._rpc("eth_chainId", [])
            responses["eth_chainId"][second] = TimeoutError("offline")
            with self.assertRaisesRegex(ProviderJuryChainError, "unavailable"):
                adapter._rpc("eth_chainId", [])
            responses["eth_gasPrice"][second] = "0x07"
            with self.assertRaisesRegex(ProviderJuryChainError, "canonical RPC hex"):
                adapter._rpc("eth_gasPrice", [])

    def test_confirmed_context_pins_both_runtimes_and_registry_policy(self) -> None:
        settlement_code, registry_code = b"settlement-runtime", b"registry-runtime"
        config = replace(
            self.config,
            settlement_runtime_code_hash="0x" + chain.keccak256(settlement_code).hex(),
            registry_runtime_code_hash="0x" + chain.keccak256(registry_code).hex(),
        )
        now = int(time.time())
        uint_values = {
            "adjudicationThreshold()": 2, "PROTOCOL_VERSION()": 10,
            "minimumReputation()": 80, "jurySize()": 3, "threshold()": 2,
            "selectionDelayBlocks()": 2,
        }
        address_values = {
            "juryRegistry()": self.registry, "settlement()": self.contract,
            "governance()": self.governance,
            "reputationAuthority()": self.reputation_authority,
            "bondPenaltyRecipient()": self.penalty,
        }
        selectors = {
            chain.encode_contract_call(signature, [])[:10]: ("uint", value)
            for signature, value in uint_values.items()
        }
        selectors.update({
            chain.encode_contract_call(signature, [])[:10]: ("address", value)
            for signature, value in address_values.items()
        })
        selectors[chain.encode_contract_call("RANDOMNESS_MODE_HASH()", [])[:10]] = (
            "hash", "0x" + chain.keccak256(b"future_blockhash_v1").hex(),
        )

        def rpc(method, params):
            if method == "eth_chainId":
                return hex(31337)
            if method == "eth_blockNumber":
                return "0x65"
            if method == "eth_getBlockByNumber" and params[0] == "0x0":
                return {"hash": digest(100)}
            if method == "eth_getBlockByNumber" and params[0] == "0x64":
                return {"number": "0x64", "hash": digest(200), "timestamp": hex(now)}
            if method == "eth_getCode":
                return "0x" + (settlement_code if params[0] == self.contract else registry_code).hex()
            if method == "eth_call":
                kind, value = selectors[params[0]["data"][:10]]
                if kind == "uint":
                    return "0x" + _word_uint(value).hex()
                if kind == "address":
                    return "0x" + _word_address(value).hex()
                return value
            self.fail(f"unexpected RPC {method} {params}")

        adapter = ProviderJuryChainAdapter(
            config, outbox_path=Path(self.temporary.name) / "context.sqlite3",
            resolve_provider=lambda _snapshot: {}, sender=self.sender, rpc=rpc,
            allow_test_rpc_override=True,
        )
        self.addCleanup(adapter.close)
        context = adapter.confirmed_context()
        self.assertEqual(context["block_number"], 100)
        self.assertEqual(context["block_hash"], digest(200))

        uint_values["threshold()"] = 3
        selectors[chain.encode_contract_call("threshold()", [])[:10]] = ("uint", 3)
        with self.assertRaisesRegex(ProviderJuryChainError, "differs from"):
            adapter.confirmed_context()

    def test_finalized_assignment_uses_immutable_snapshot_not_live_roster(self) -> None:
        identities = [create_identity() for _ in range(3)]
        policy_hash = provider_jury.decision_policy_hash(
            model="judge-model",
            system_prompt="Apply the pinned policy.",
            max_output_tokens=512,
            task_ttl_seconds=300,
        )
        capability = {
            "schema": provider_jury.CAPABILITY_SCHEMA, "models": ["judge-model"],
            "max_output_tokens": 1024, "supports_structured_verdict": True,
            "decision_policy_hash": policy_hash,
        }
        descriptors = []
        for index, identity in enumerate(identities):
            operator = f"operator-{index}"
            descriptors.append({
                "owner": address(100 + index), "vote_signer": signer(20 + index),
                "operator_id": operator,
                "operator_id_hash": provider_jury._keccak_text(operator),
                "peer_id": identity.peer_id,
                "peer_id_hash": provider_jury._keccak_text(identity.peer_id),
                "capability": capability,
                "capability_hash": provider_jury.capability_hash(capability),
                "reputation": 90 + index,
            })
        by_signer = {item["vote_signer"]: item for item in descriptors}
        adapter = self.adapter(
            resolver=lambda snapshot: by_signer[snapshot["vote_signer"]],
        )
        self.addCleanup(adapter.close)
        case_id, seed = digest(7), digest(8)
        expected = assignment_hash(
            registry=self.registry, chain_id=31337, settlement=self.contract,
            case_id=case_id, roster_version=9, seed=seed,
            minimum_reputation=80, jury_size=3, threshold=2,
            owners=[item["owner"] for item in descriptors],
            vote_signers=[item["vote_signer"] for item in descriptors],
            operator_id_hashes=[item["operator_id_hash"] for item in descriptors],
            peer_id_hashes=[item["peer_id_hash"] for item in descriptors],
            capability_hashes=[item["capability_hash"] for item in descriptors],
            reputations=[item["reputation"] for item in descriptors],
        )
        adapter.confirmed_context = lambda: {
            "block_number": 123, "block_hash": digest(9), "timestamp": int(time.time()),
            "block_tag": {"blockHash": digest(9), "requireCanonical": True},
        }
        adapter._assert_context_canonical = lambda _context: None
        adapter._assignment_info = lambda _key, _tag: {
            "status_code": 2, "selection_block": 100, "roster_version": 9,
            "seed": seed, "result_hash": expected,
            "owners": [item["owner"] for item in descriptors],
            "vote_signers": [item["vote_signer"] for item in descriptors],
            "operator_id_hashes": [item["operator_id_hash"] for item in descriptors],
        }
        adapter._assignment_evidence = lambda _key, _tag: {
            "peer_id_hashes": [item["peer_id_hash"] for item in descriptors],
            "capability_hashes": [item["capability_hash"] for item in descriptors],
            "reputations": [item["reputation"] for item in descriptors],
        }
        adapter._assignment_signer_snapshot = lambda _key, vote_signer, _tag: {
            "found": True,
            **{name: value for name, value in by_signer[vote_signer].items()
               if name in {"owner", "operator_id_hash", "peer_id_hash",
                           "capability_hash", "reputation"}},
        }
        adapter._call_words = lambda _target, signature, _args, count, _tag: (
            [bytes.fromhex(expected[2:])]
            if signature == "assignmentHash(bytes32)" and count == 1 else
            self.fail("unexpected chain read")
        )
        binding = {
            "schema": "mycomesh.v10.provider-jury-case.v1", "network_id": "fixture",
            "chain_id": 31337, "settlement_contract": self.contract,
            "jury_registry": self.registry, "settlement_key": case_id,
        }
        result = adapter.fetch_assignment(binding)
        self.assertEqual(result["assignment_hash"], expected)
        self.assertEqual(result["selected_providers"], descriptors)

        # A resolver cannot substitute current/live roster metadata for the
        # immutable per-case capability snapshot.
        changed = dict(descriptors[0])
        changed["reputation"] += 1
        adapter.resolve_provider = lambda snapshot: (
            changed if snapshot["vote_signer"] == changed["vote_signer"]
            else by_signer[snapshot["vote_signer"]]
        )
        with self.assertRaisesRegex(ProviderJuryChainError, "differs from"):
            adapter.fetch_assignment(binding)

    def test_assignment_info_decoder_rejects_noncanonical_dynamic_offsets(self) -> None:
        adapter = self.adapter()
        self.addCleanup(adapter.close)
        owners = [address(1), address(2), address(3)]
        signers = [address(11), address(12), address(13)]
        operators = [digest(21), digest(22), digest(23)]
        arrays = [
            _word_uint(len(owners)) + b"".join(_word_address(item) for item in owners),
            _word_uint(len(signers)) + b"".join(_word_address(item) for item in signers),
            _word_uint(len(operators)) + b"".join(_word_hash(item) for item in operators),
        ]
        offsets, cursor = [], 8 * 32
        for item in arrays:
            offsets.append(cursor)
            cursor += len(item)
        head = b"".join((
            _word_uint(2), _word_uint(100), _word_uint(9), _word_hash(digest(8)),
            _word_hash(digest(9)), *(_word_uint(item) for item in offsets),
        ))
        encoded = head + b"".join(arrays)
        adapter._call = lambda *_args, **_kwargs: encoded
        decoded = adapter._assignment_info(digest(7), "latest")
        self.assertEqual(decoded["owners"], owners)
        self.assertEqual(decoded["vote_signers"], signers)

        malformed = bytearray(encoded)
        malformed[6 * 32:7 * 32] = _word_uint(offsets[1] + 32)
        adapter._call = lambda *_args, **_kwargs: bytes(malformed)
        with self.assertRaisesRegex(ProviderJuryChainError, "noncanonical array offsets"):
            adapter._assignment_info(digest(7), "latest")

    def test_outbox_crash_recovery_never_reuses_or_blindly_resends_nonce(self) -> None:
        path = Path(self.temporary.name) / "outbox.sqlite3"
        action = self.action_fixture()
        outbox = JuryTransactionOutbox(path)
        saved = outbox.reserve(
            action=action, scope=f"{digest(100)}:31337", sender=self.sender,
            nonce=7, target=self.contract, calldata="0x1234",
            gas_price_wei=1, gas_units=100_000,
            raw_tx=self.signed_raw(action, nonce=7),
        )
        outbox.begin_send(action["action_hash"])
        outbox.close()

        recovered = JuryTransactionOutbox(path)
        self.addCleanup(recovered.close)
        self.assertEqual(recovered.get(action["action_hash"])["state"], "uncertain")
        storage = recovered.storage_health()
        self.assertTrue(storage["ready"])
        self.assertEqual(storage["backlog_count"], 1)
        self.assertEqual(storage["uncertain_count"], 1)
        next_action = self.action_fixture(calldata="0x5678")
        with self.assertRaisesRegex(ProviderJuryChainError, "unresolved"):
            recovered.reserve(
                action=next_action,
                scope=f"{digest(100)}:31337", sender=self.sender, nonce=8,
                target=self.contract, calldata="0x5678", gas_price_wei=1,
                gas_units=100_000,
                raw_tx=self.signed_raw(next_action, nonce=8),
            )
        self.assertEqual(recovered.get(action["action_hash"])["tx_hash"], saved["tx_hash"])

    def test_outbox_revalidates_paired_raw_transaction_and_hash_against_plan(self) -> None:
        outbox = JuryTransactionOutbox(Path(self.temporary.name) / "tamper.sqlite3")
        self.addCleanup(outbox.close)
        action = self.action_fixture()
        outbox.reserve(
            action=action, scope=f"{digest(100)}:31337", sender=self.sender,
            nonce=7, target=self.contract, calldata="0x1234",
            gas_price_wei=1, gas_units=100_000,
            raw_tx=self.signed_raw(action, nonce=7),
        )
        changed = self.signed_raw(action, nonce=7, gas_units=90_000)
        outbox.db.execute(
            "UPDATE provider_jury_chain_transactions SET raw_tx=?,tx_hash=? "
            "WHERE action_hash=?",
            (
                "0x" + changed.hex(), "0x" + chain.keccak256(changed).hex(),
                action["action_hash"],
            ),
        )
        with self.assertRaisesRegex(ProviderJuryChainError, "differs from its durable plan"):
            outbox.get(action["action_hash"])

    def test_stored_raw_transaction_binds_every_signed_plan_field(self) -> None:
        outbox = JuryTransactionOutbox(Path(self.temporary.name) / "raw-fields.sqlite3")
        self.addCleanup(outbox.close)
        action = self.action_fixture()
        raw = self.signed_raw(action, nonce=7)
        saved = outbox.reserve(
            action=action, scope=f"{digest(100)}:31337", sender=self.sender,
            nonce=7, target=self.contract, calldata="0x1234",
            gas_price_wei=1, gas_units=100_000, raw_tx=raw,
        )
        row = outbox.db.execute(
            "SELECT * FROM provider_jury_chain_transactions WHERE action_hash=?",
            (action["action_hash"],),
        ).fetchone()
        plan = json.loads(row["transaction_plan_json"])
        provider_jury_chain._verify_signed_transaction(
            plan, row["raw_tx"], saved["tx_hash"],
        )
        mutations = (
            {"chain_id": 31338}, {"key_number": 91}, {"nonce": 8},
            {"gas_price_wei": 2}, {"gas_units": 99_999},
            {"target": self.registry}, {"value": 1}, {"calldata": "0x5678"},
        )
        for mutation in mutations:
            with self.subTest(mutation=mutation):
                parameters = {"nonce": 7, **mutation}
                changed = self.signed_raw(action, **parameters)
                changed_hash = "0x" + chain.keccak256(changed).hex()
                with self.assertRaisesRegex(
                    ProviderJuryChainError, "differs from its durable plan",
                ):
                    provider_jury_chain._verify_signed_transaction(
                        plan, "0x" + changed.hex(), changed_hash,
                    )
        with self.assertRaisesRegex(ProviderJuryChainError, "hash mismatch"):
            provider_jury_chain._verify_signed_transaction(
                plan, row["raw_tx"], digest(999),
            )

    @unittest.skipIf(os.name == "nt", "hard links use different Windows semantics")
    def test_outbox_rejects_unsafe_paths_and_detects_open_time_swap(self) -> None:
        original = Path(self.temporary.name) / "linked.sqlite3"
        original.touch(mode=0o600)
        alias = Path(self.temporary.name) / "linked-alias.sqlite3"
        os.link(original, alias)
        with self.assertRaisesRegex(ProviderJuryChainError, "exactly one link"):
            JuryTransactionOutbox(alias)

        unsafe = Path(self.temporary.name) / "unsafe"
        unsafe.mkdir(mode=0o700)
        unsafe.chmod(0o777)
        try:
            with self.assertRaisesRegex(ProviderJuryChainError, "parent must be owned"):
                JuryTransactionOutbox(unsafe / "outbox.sqlite3")
        finally:
            unsafe.chmod(0o700)

        path = Path(self.temporary.name) / "swapped.sqlite3"
        displaced = Path(self.temporary.name) / "displaced.sqlite3"
        real_connect = provider_jury_chain.sqlite3.connect

        def swap_then_connect(database, *args, **kwargs):
            Path(database).rename(displaced)
            Path(database).touch(mode=0o600)
            Path(database).chmod(0o600)
            return real_connect(database, *args, **kwargs)

        with mock.patch.object(
            provider_jury_chain.sqlite3, "connect", side_effect=swap_then_connect,
        ):
            with self.assertRaisesRegex(
                ProviderJuryChainError, "changed after its protected open",
            ):
                JuryTransactionOutbox(path)

        # Reject attacker-controlled SQLite sidecars before sqlite3 gets an
        # opportunity to follow or modify them.
        sidecar_path = Path(self.temporary.name) / "sidecar.sqlite3"
        sidecar_path.touch(mode=0o600)
        sidecar_path.chmod(0o600)
        victim = Path(self.temporary.name) / "sidecar-victim"
        victim.touch(mode=0o600)
        Path(str(sidecar_path) + "-wal").symlink_to(victim)
        with self.assertRaisesRegex(ProviderJuryChainError, "sidecar is unsafe"):
            JuryTransactionOutbox(sidecar_path)

    def test_sender_lock_is_cross_outbox_and_rejects_key_aliases(self) -> None:
        key_file = Path(self.temporary.name) / "sender.key"
        key_file.write_text(key(90), encoding="ascii")
        key_file.chmod(0o600)
        with provider_jury_chain._jury_sender_lock(key_file, self.sender):
            with self.assertRaisesRegex(ProviderJuryChainError, "another jury process"):
                with provider_jury_chain._jury_sender_lock(key_file, self.sender):
                    self.fail("same sender acquired two outbox locks")

        hard_link = Path(self.temporary.name) / "sender-hard-link.key"
        os.link(key_file, hard_link)
        with self.assertRaisesRegex(ProviderJuryChainError, "exactly one link"):
            with provider_jury_chain._jury_sender_lock(key_file, self.sender):
                self.fail("hard-linked key acquired a sender lock")

        if os.getuid() != 0:
            isolated = Path(self.temporary.name) / "isolated"
            isolated.mkdir(mode=0o700)
            isolated_key = isolated / "sender.key"
            isolated_key.write_text(key(90), encoding="ascii")
            isolated_key.chmod(0o600)
            parent_alias = Path(self.temporary.name) / "key-alias"
            parent_alias.symlink_to(isolated, target_is_directory=True)
            with self.assertRaisesRegex(ProviderJuryChainError, "symbolic link"):
                with provider_jury_chain._jury_sender_lock(
                    parent_alias / "sender.key", self.sender,
                ):
                    self.fail("symlinked key ancestor acquired a sender lock")

    def test_sender_lock_binds_open_key_inode_against_path_swap(self) -> None:
        key_file = Path(self.temporary.name) / "swapped-sender.key"
        key_file.write_text(key(90), encoding="ascii")
        key_file.chmod(0o600)
        displaced = Path(self.temporary.name) / "displaced-sender.key"
        canonical = Path(os.path.realpath(key_file))
        real_open = provider_jury_chain.os.open
        swapped = False

        def open_then_swap(path, flags, mode=0o777):
            nonlocal swapped
            descriptor = real_open(path, flags, mode)
            if not swapped and Path(path) == canonical:
                swapped = True
                key_file.rename(displaced)
                key_file.write_text(key(90), encoding="ascii")
                key_file.chmod(0o600)
            return descriptor

        with mock.patch.object(
            provider_jury_chain.os, "open", side_effect=open_then_swap,
        ):
            with self.assertRaisesRegex(
                ProviderJuryChainError, "changed after its protected open",
            ):
                with provider_jury_chain._jury_sender_lock(key_file, self.sender):
                    self.fail("swapped key path acquired a sender lock")

    def test_outbox_storage_health_fails_closed_when_readonly_or_closed(self) -> None:
        path = Path(self.temporary.name) / "health.sqlite3"
        outbox = JuryTransactionOutbox(path)
        healthy = outbox.storage_health()
        self.assertTrue(healthy["ready"])
        self.assertTrue(healthy["quick_check"])
        self.assertTrue(healthy["writable"])
        self.assertEqual(healthy["backlog_count"], 0)
        self.assertEqual(healthy["uncertain_count"], 0)

        outbox.db.execute("PRAGMA query_only=ON")
        readonly = outbox.storage_health()
        self.assertFalse(readonly["ready"])
        self.assertTrue(readonly["quick_check"])
        self.assertFalse(readonly["writable"])
        outbox.db.execute("PRAGMA query_only=OFF")

        outbox.close()
        closed = outbox.storage_health()
        self.assertFalse(closed["ready"])
        self.assertFalse(closed["quick_check"])
        self.assertFalse(closed["writable"])

        path.write_bytes(b"not-a-sqlite-database")
        outbox.db = sqlite3.connect(
            path, timeout=30, isolation_level=None, check_same_thread=False,
        )
        damaged = outbox.storage_health()
        self.assertFalse(damaged["ready"])
        self.assertFalse(damaged["quick_check"])
        outbox.close()

    def test_broadcast_timeout_is_persisted_and_never_automatically_retried(self) -> None:
        key_file = Path(self.temporary.name) / "jury.key"
        key_file.write_text(key(90), encoding="ascii")
        os.chmod(key_file, 0o600)
        sends = []

        def rpc(method, _params):
            if method == "eth_chainId":
                return hex(31337)
            if method == "eth_getBlockByNumber":
                return {"hash": digest(100)}
            if method == "eth_getTransactionCount":
                return "0x0"
            if method == "eth_gasPrice":
                return "0x1"
            if method == "eth_estimateGas":
                return "0x5208"
            if method == "eth_sendRawTransaction":
                sends.append(1)
                raise TimeoutError("response lost")
            self.fail(f"unexpected RPC {method}")

        adapter = self.adapter(
            name="broadcast.sqlite3", rpc=rpc, execution_enabled=True,
            dedicated_sender=True, key_file=key_file, max_gas_price_wei=10,
            max_gas_units=100_000, max_total_gas_cost_wei=1_000_000,
        )
        self.addCleanup(adapter.close)
        body = {
            "schema": TRANSACTION_SCHEMA, "action": "vote_dispute_by_sig",
            "network_id": "fixture", "chain_id": 31337,
            "genesis_hash": digest(100), "sender": self.sender,
            "target": self.contract, "value": 0, "calldata": "0x1234",
            "settlement_key": digest(7),
        }
        action = {**body, "action_hash": evidence_hash(body)}
        with self.assertRaisesRegex(ProviderJuryChainError, "uncertain"):
            adapter._submit(action)
        self.assertEqual(adapter.outbox.get(action["action_hash"])["state"], "uncertain")
        with self.assertRaisesRegex(ProviderJuryChainError, "reconcile"):
            adapter._submit(action)
        self.assertEqual(len(sends), 1)

    def test_multi_rpc_broadcast_divergence_is_durable_uncertain(self) -> None:
        key_file = Path(self.temporary.name) / "quorum-jury.key"
        key_file.write_text(key(90), encoding="ascii")
        key_file.chmod(0o600)
        adapter = self.adapter(
            name="quorum-broadcast.sqlite3", execution_enabled=True,
            dedicated_sender=True, key_file=key_file, max_gas_price_wei=10,
            max_gas_units=100_000, max_total_gas_cost_wei=1_000_000,
        )
        self.addCleanup(adapter.close)
        first, second = self.config.rpc_urls

        def rpc(endpoint, method, params, _timeout):
            if method == "eth_chainId":
                return hex(31337)
            if method == "eth_getBlockByNumber":
                return {"hash": digest(100)}
            if method == "eth_getTransactionCount":
                return "0x0"
            if method == "eth_gasPrice":
                return "0x1" if endpoint == first else "0x2"
            if method == "eth_estimateGas":
                return "0x5208"
            if method == "eth_sendRawTransaction":
                raw = bytes.fromhex(params[0][2:])
                if endpoint == first:
                    return "0x" + chain.keccak256(raw).hex()
                raise TimeoutError("response lost")
            self.fail(f"unexpected RPC {method} {params}")

        action = self.action_fixture()
        with mock.patch.object(provider_jury_chain.chain, "rpc_call", side_effect=rpc):
            with self.assertRaisesRegex(ProviderJuryChainError, "uncertain"):
                adapter._submit(action)
        stored = adapter.outbox.get(action["action_hash"])
        self.assertIsNotNone(stored)
        self.assertEqual(stored["state"], "uncertain")

    def test_broadcast_failure_before_outbox_is_definitely_not_sent(self) -> None:
        adapter = self.adapter(name="not-sent.sqlite3")
        self.addCleanup(adapter.close)
        body = {
            "schema": TRANSACTION_SCHEMA, "action": "vote_dispute_by_sig",
            "network_id": "fixture", "chain_id": 31337,
            "genesis_hash": digest(100), "sender": self.sender,
            "target": self.contract, "value": 0, "calldata": "0x1234",
            "settlement_key": digest(7), "source_plan_hash": digest(8),
        }
        action = {**body, "action_hash": evidence_hash(body)}
        adapter._preflight_vote = lambda _plan: action

        def fail_before_reserve(_action):
            raise ProviderJuryChainError("gas cap")

        adapter._submit = fail_before_reserve
        with self.assertRaises(ProviderJuryDefinitelyNotSentError):
            adapter.broadcast({"plan_hash": digest(8)})
        self.assertIsNone(adapter.outbox.get(action["action_hash"]))

    def test_negative_preflight_reuses_full_assignment_nonce_and_simulation_fences(self) -> None:
        adapter = self.adapter(name="negative-preflight.sqlite3")
        self.addCleanup(adapter.close)
        case_id, assignment_id = digest(7), digest(8)
        evidence_report, evidence_commitment = digest(9), digest(10)
        decision_hash = digest(11)
        timestamp = int(time.time())
        selected = [
            {"vote_signer": signer(20 + index)} for index in range(3)
        ]
        permits = [
            chain_v10.build_dispute_vote(
                settlement_key=case_id,
                assignment_hash=assignment_id,
                confirmed=False,
                report_id=ZERO_BYTES32,
                decision_hash=decision_hash,
                nonce=0,
                deadline=timestamp + 120,
                judge_private_key=key(20 + index),
                chain_id=self.config.chain_id,
                settlement_contract=self.contract,
            )
            for index in range(2)
        ]
        vote = {
            "chain_id": self.config.chain_id,
            "settlement_contract": self.contract,
            "settlement_key": case_id,
            "assignment_hash": assignment_id,
            "confirmed": False,
            "report_id": ZERO_BYTES32,
            "decision_hash": decision_hash,
            "to": self.contract,
            "value": "0x0",
            "votes": [
                {name: permit[name] for name in (
                    "judge", "nonce", "deadline", "signature",
                )}
                for permit in permits
            ],
            "vote_permits": permits,
            "data": chain_v10.encode_dispute_vote_by_sig(case_id, permits),
            "broadcast": False,
        }
        body = {
            "schema": "mycomesh.v10.provider-jury-execution-plan.v1",
            "assignment": {
                "assignment_hash": assignment_id,
                "selected_providers": selected,
            },
            "evidence": {
                "report_id": evidence_report,
                "evidence_hash": evidence_commitment,
                "request_hash": digest(12),
                "response_hash": digest(13),
            },
            "evm_vote": vote,
            "automatic_execution_allowed": True,
        }
        plan = {**body, "plan_hash": evidence_hash(body)}
        adapter._read_assignment = lambda _binding, resolve: {
            "status": "finalized",
            "assignment_hash": assignment_id,
            "selected_providers": selected,
        }
        tag = {"blockHash": digest(14), "requireCanonical": True}
        adapter.confirmed_context = lambda: {
            "block_tag": tag, "timestamp": timestamp,
            "block_number": 100, "block_hash": digest(14),
        }
        adapter._settlement_snapshot = lambda _key, _tag: {
            "owner": address(1), "key": address(2), "provider": address(3),
            "provider_signer": address(4), "relay": address(5),
            "relay_signer": address(6), "pool": chain.ZERO_ADDRESS,
            "treasury": address(7), "request_hash": digest(12),
            "response_hash": digest(13), "release_at": timestamp - 1,
            "status": 2,
        }
        adapter._dispute_snapshot = lambda _key, _tag: {
            "resolve_at": timestamp + 60,
        }
        reads: list[str] = []

        def call_words(_target, signature, args, count, _tag):
            reads.append(signature)
            if signature == "assignmentHash(bytes32)":
                return [bytes.fromhex(assignment_id[2:])]
            if signature == "reports(bytes32,bytes32)":
                self.assertEqual(args, [case_id, evidence_report])
                return [
                    _word_address(address(1)),
                    _word_hash(evidence_commitment),
                    _word_uint(0),
                ]
            if signature in {
                "adjudicatorNonce(bytes32,address)",
                "disputeVotes(bytes32,address)",
            }:
                return [_word_uint(0)]
            self.fail(f"unexpected preflight read {signature} {count}")

        adapter._call_words = call_words
        simulations = []
        adapter._rpc_override = lambda method, params: (
            simulations.append((method, params)) or "0x"
        )
        action = adapter._preflight_vote(plan)
        self.assertFalse(action["vote_confirmed"])
        self.assertEqual(action["vote_report_id"], ZERO_BYTES32)
        self.assertEqual(action["vote_judges"], [signer(20), signer(21)])
        self.assertNotIn("hasReported(bytes32,address)", reads)
        self.assertEqual(simulations[0][0], "eth_call")

    def test_receipt_reconcile_checks_transaction_nonce_and_exact_vote_events(self) -> None:
        report_id, decision_hash = digest(31), digest(32)
        action = self.action_fixture(
            vote_confirmed=True, vote_report_id=report_id,
            vote_decision_hash=decision_hash,
            vote_judges=[signer(20), signer(21)],
        )
        outbox_path = Path(self.temporary.name) / "receipt.sqlite3"
        outbox = JuryTransactionOutbox(outbox_path)
        raw = self.signed_raw(action, nonce=7)
        row = outbox.reserve(
            action=action, scope=f"{digest(100)}:31337", sender=self.sender,
            nonce=7, target=self.contract, calldata="0x1234",
            gas_price_wei=1, gas_units=100_000, raw_tx=raw,
        )
        # Model a lost broadcast response followed by a process restart.  The
        # restarted adapter must reconcile the exact persisted identity rather
        # than re-signing or rebroadcasting it.
        outbox.mark(action["action_hash"], "uncertain")
        outbox.close()
        block_hash = digest(201)
        event_data = _word_uint(1) + _word_hash(report_id) + _word_hash(decision_hash)
        log = {
            "address": self.contract,
            "topics": [DISPUTE_VOTE_TOPIC, digest(7), topic_address(signer(20))],
            "data": "0x" + event_data.hex(), "transactionHash": row["tx_hash"],
            "blockHash": block_hash, "blockNumber": "0x64", "logIndex": "0x2",
            "removed": False,
        }
        second_log = {
            **log,
            "topics": [DISPUTE_VOTE_TOPIC, digest(7), topic_address(signer(21))],
            "logIndex": "0x3",
        }
        resolution_log = {
            "address": self.contract,
            "topics": [DISPUTE_RESOLVED_TOPIC, digest(7)],
            "data": "0x" + (_word_uint(4) + _word_uint(10) + _word_uint(2)).hex(),
            "transactionHash": row["tx_hash"], "blockHash": block_hash,
            "blockNumber": "0x64", "logIndex": "0x4", "removed": False,
        }
        transaction = {
            "hash": row["tx_hash"], "from": self.sender, "to": self.contract,
            "nonce": "0x7", "value": "0x0", "input": "0x1234",
            "chainId": hex(31337), "blockNumber": "0x64", "blockHash": block_hash,
        }
        receipt = {
            "transactionHash": row["tx_hash"], "from": self.sender, "to": self.contract,
            "blockNumber": "0x64", "blockHash": block_hash, "status": "0x1",
            "logs": [log, second_log, resolution_log],
        }

        def rpc(method, params):
            if method == "eth_chainId":
                return hex(31337)
            if method == "eth_getTransactionByHash":
                return transaction
            if method == "eth_getTransactionReceipt":
                return receipt
            if method == "eth_blockNumber":
                return "0x65"
            if method == "eth_getBlockByNumber" and params[0] == "0x0":
                return {"hash": digest(100)}
            if method == "eth_getBlockByNumber" and params[0] == "0x64":
                return {"hash": block_hash, "number": "0x64"}
            self.fail(f"unexpected RPC {method} {params}")

        adapter = self.adapter(
            name="receipt.sqlite3", rpc=rpc,
        )
        self.addCleanup(adapter.close)
        self.assertEqual(
            adapter.outbox.get(action["action_hash"])["state"], "uncertain",
        )
        adapter._settlement_snapshot = lambda _key, _tag: {"status": 4}
        adapter._dispute_snapshot = lambda _key, _tag: {
            "opened_at": 1, "resolve_at": 2, "dismiss_votes": 0,
            "report_count": 1, "total_bond": 5,
            "winning_report_id": report_id, "slash_amount": 10,
            "stable_bounty": 2,
        }
        observed = adapter._inspect_action(action, adapter.outbox.get(action["action_hash"]))
        self.assertEqual(observed["status"], "confirmed")
        self.assertEqual(
            adapter.outbox.get(action["action_hash"])["state"], "confirmed",
        )
        self.assertEqual(observed["nonce"], 7)
        self.assertEqual(observed["vote_events"][0]["decision_hash"], decision_hash)
        self.assertEqual(observed["resolution_event"]["status"], 4)
        self.assertFalse(observed["settlement_outcome"]["report_bond_forfeited"])

        # A receipt cannot be attached to a transaction with a different nonce.
        transaction["nonce"] = "0x8"
        with self.assertRaisesRegex(ProviderJuryChainError, "identity differs"):
            adapter._inspect_action(action, adapter.outbox.get(action["action_hash"]))

    def test_negative_receipt_proves_dismissed_state_and_bond_forfeiture(self) -> None:
        case_id, decision_hash = digest(71), digest(72)
        action = self.action_fixture(
            calldata="0x5678", settlement_key=case_id,
            vote_confirmed=False, vote_report_id=ZERO_BYTES32,
            vote_decision_hash=decision_hash,
            vote_judges=[signer(20), signer(21)],
        )
        outbox_path = Path(self.temporary.name) / "dismiss-receipt.sqlite3"
        outbox = JuryTransactionOutbox(outbox_path)
        row = outbox.reserve(
            action=action, scope=f"{digest(100)}:31337", sender=self.sender,
            nonce=8, target=self.contract, calldata="0x5678",
            gas_price_wei=1, gas_units=100_000,
            raw_tx=self.signed_raw(action, nonce=8),
        )
        outbox.mark(action["action_hash"], "submitted")
        outbox.close()
        block_hash = digest(273)
        vote_data = _word_uint(0) + _word_hash(ZERO_BYTES32) + _word_hash(decision_hash)
        vote_logs = [
            {
                "address": self.contract,
                "topics": [DISPUTE_VOTE_TOPIC, case_id, topic_address(judge)],
                "data": "0x" + vote_data.hex(),
                "transactionHash": row["tx_hash"], "blockHash": block_hash,
                "blockNumber": "0x64", "logIndex": hex(index), "removed": False,
            }
            for index, judge in enumerate((signer(20), signer(21)))
        ]
        resolution_log = {
            "address": self.contract,
            "topics": [DISPUTE_RESOLVED_TOPIC, case_id],
            "data": "0x" + (_word_uint(5) + _word_uint(0) + _word_uint(0)).hex(),
            "transactionHash": row["tx_hash"], "blockHash": block_hash,
            "blockNumber": "0x64", "logIndex": "0x2", "removed": False,
        }
        transaction = {
            "hash": row["tx_hash"], "from": self.sender, "to": self.contract,
            "nonce": "0x8", "value": "0x0", "input": "0x5678",
            "chainId": hex(31337), "blockNumber": "0x64", "blockHash": block_hash,
        }
        receipt = {
            "transactionHash": row["tx_hash"], "from": self.sender,
            "to": self.contract, "blockNumber": "0x64",
            "blockHash": block_hash, "status": "0x1",
            "logs": [*vote_logs, resolution_log],
        }

        def rpc(method, params):
            if method == "eth_chainId":
                return hex(31337)
            if method == "eth_getTransactionByHash":
                return transaction
            if method == "eth_getTransactionReceipt":
                return receipt
            if method == "eth_blockNumber":
                return "0x65"
            if method == "eth_getBlockByNumber" and params[0] == "0x0":
                return {"hash": digest(100)}
            if method == "eth_getBlockByNumber" and params[0] == "0x64":
                return {"hash": block_hash, "number": "0x64"}
            self.fail(f"unexpected RPC {method} {params}")

        adapter = self.adapter(name="dismiss-receipt.sqlite3", rpc=rpc)
        self.addCleanup(adapter.close)
        adapter._settlement_snapshot = lambda _key, _tag: {"status": 5}
        adapter._dispute_snapshot = lambda _key, _tag: {
            "opened_at": 1, "resolve_at": 2, "dismiss_votes": 2,
            "report_count": 1, "total_bond": 5,
            "winning_report_id": ZERO_BYTES32, "slash_amount": 0,
            "stable_bounty": 0,
        }
        observed = adapter._inspect_action(
            action, adapter.outbox.get(action["action_hash"]),
        )
        self.assertEqual(observed["status"], "confirmed")
        self.assertTrue(observed["settlement_outcome"]["report_bond_forfeited"])
        self.assertEqual(observed["settlement_outcome"]["status"], "dismissed")

        adapter.outbox.mark(action["action_hash"], "submitted")
        resolution_log["data"] = "0x" + (
            _word_uint(4) + _word_uint(0) + _word_uint(0)
        ).hex()
        with self.assertRaisesRegex(ProviderJuryChainError, "wrong jury outcome"):
            adapter._inspect_action(action, adapter.outbox.get(action["action_hash"]))

    def test_finalize_event_is_bound_to_case_hash_and_full_selected_arrays(self) -> None:
        adapter = self.adapter(name="event.sqlite3")
        self.addCleanup(adapter.close)
        case_id, result_hash, seed = digest(7), digest(8), digest(9)
        owners = [address(1), address(2), address(3)]
        signers = [address(11), address(12), address(13)]
        operators = [digest(21), digest(22), digest(23)]
        arrays = [
            _word_uint(3) + b"".join(_word_address(item) for item in owners),
            _word_uint(3) + b"".join(_word_address(item) for item in signers),
            _word_uint(3) + b"".join(_word_hash(item) for item in operators),
        ]
        cursor, offsets = 4 * 32, []
        for item in arrays:
            offsets.append(cursor)
            cursor += len(item)
        data = _word_hash(seed) + b"".join(_word_uint(item) for item in offsets) + b"".join(arrays)
        tx_hash, block_hash = digest(30), digest(31)
        receipt = {"transaction_hash": tx_hash, "block_hash": block_hash, "block_number": 100}
        log = {
            "address": self.registry,
            "topics": [JURY_ASSIGNED_TOPIC, case_id, result_hash],
            "data": "0x" + data.hex(), "transactionHash": tx_hash,
            "blockHash": block_hash, "blockNumber": "0x64", "logIndex": "0x0",
            "removed": False,
        }
        event = adapter._finalize_event(
            [log], receipt=receipt,
            action={"settlement_key": case_id},
        )
        self.assertEqual(event["assignment_hash"], result_hash)
        self.assertEqual(event["owners"], owners)
        self.assertEqual(event["vote_signers"], signers)
        self.assertEqual(event["operator_id_hashes"], operators)

        failed_log = {
            **log,
            "topics": [JURY_FAILED_TOPIC, case_id],
            "data": ZERO_BYTES32,
        }
        failed_event = adapter._finalize_event(
            [failed_log], receipt=receipt, action={"settlement_key": case_id},
        )
        self.assertEqual(
            failed_event, {"event": "JuryAssignmentFailed", "seed": ZERO_BYTES32},
        )
        with self.assertRaisesRegex(ProviderJuryChainError, "one terminal"):
            adapter._finalize_event(
                [failed_log, failed_log], receipt=receipt,
                action={"settlement_key": case_id},
            )

    def test_expire_assignment_requires_elapsed_window_and_zero_seed_failure_event(self) -> None:
        adapter = self.adapter(name="expire.sqlite3")
        self.addCleanup(adapter.close)
        case_id = digest(7)
        binding = {
            "schema": "mycomesh.v10.provider-jury-case.v1", "network_id": "fixture",
            "chain_id": 31337, "settlement_contract": self.contract,
            "jury_registry": self.registry, "settlement_key": case_id,
        }
        pending = {
            **binding, "status": "pending", "selection_block": 100,
            "roster_version": 9, "block_number": 357, "block_hash": digest(9),
        }
        failed = {
            **binding, "status": "failed", "seed": ZERO_BYTES32,
            "block_number": 360, "block_hash": digest(10),
        }
        states = iter((pending, failed))
        adapter._read_assignment = lambda _binding, resolve: next(states)
        adapter._call = lambda target, signature, args, tag, sender=None: (
            b"" if (target, signature, args, sender) == (
                self.registry, "expireJury(bytes32)", [case_id], self.sender,
            ) else self.fail("unexpected expire preflight")
        )
        submitted = []

        def submit(action):
            submitted.append(action)
            return {
                "action_hash": action["action_hash"], "target": action["target"],
                "calldata": action["calldata"], "tx_hash": digest(80),
                "sender": self.sender, "nonce": 7, "state": "submitted",
            }

        adapter._submit = submit
        adapter._inspect_action = lambda _action, _row: {
            "status": "confirmed",
            "assignment_event": {"event": "JuryAssignmentFailed", "seed": ZERO_BYTES32},
        }
        result = adapter.expire_assignment(binding)
        self.assertEqual(result["status"], "failed")
        self.assertEqual(len(submitted), 1)
        self.assertEqual(
            submitted[0]["calldata"],
            chain.encode_contract_call("expireJury(bytes32)", [case_id]),
        )

        too_early = {**pending, "block_number": 356}
        adapter._read_assignment = lambda _binding, resolve: too_early
        with self.assertRaisesRegex(ProviderJuryChainError, "has not expired"):
            adapter.expire_assignment({**binding, "settlement_key": digest(71)})

        other = self.adapter(name="expire-wrong-event.sqlite3")
        self.addCleanup(other.close)
        other_states = iter((pending, failed))
        other._read_assignment = lambda _binding, resolve: next(other_states)
        other._call = adapter._call
        other._submit = submit
        other._inspect_action = lambda _action, _row: {
            "status": "confirmed",
            "assignment_event": {"event": "JuryAssignmentFailed", "seed": digest(1)},
        }
        with self.assertRaisesRegex(ProviderJuryChainError, "zero-seed"):
            other.expire_assignment(binding)

    def test_expire_action_identity_is_scoped_to_one_retry_round(self) -> None:
        adapter = self.adapter(name="expire-rounds.sqlite3")
        self.addCleanup(adapter.close)
        case_id = digest(7)
        first = {
            "settlement_key": case_id, "status": "pending",
            "selection_block": 100, "roster_version": 9,
            "block_number": 357, "block_hash": digest(90),
        }
        same_round_later_snapshot = {
            **first, "block_number": 400, "block_hash": digest(91),
        }
        second = {
            **first, "selection_block": 500,
            "block_number": 757, "block_hash": digest(92),
        }
        first_action = adapter._expire_action(first)
        self.assertEqual(
            first_action["action_hash"],
            adapter._expire_action(same_round_later_snapshot)["action_hash"],
        )
        self.assertNotEqual(
            first_action["action_hash"], adapter._expire_action(second)["action_hash"],
        )
        self.assertEqual(first_action["source_roster_version"], 9)
        self.assertEqual(first_action["source_selection_block"], 100)

    def test_retry_assignment_success_returns_pending_without_finalizing(self) -> None:
        adapter = self.adapter(name="retry-success.sqlite3")
        self.addCleanup(adapter.close)
        case_id = digest(7)
        binding = {
            "schema": "mycomesh.v10.provider-jury-case.v1", "network_id": "fixture",
            "chain_id": 31337, "settlement_contract": self.contract,
            "jury_registry": self.registry, "settlement_key": case_id,
        }
        failed = {
            **binding, "status": "failed", "seed": ZERO_BYTES32,
            "selection_block": 0, "roster_version": 9,
            "block_number": 120, "block_hash": digest(90),
        }
        pending = {
            **binding, "status": "pending", "selection_block": 125,
            "roster_version": 10, "block_number": 123, "block_hash": digest(91),
        }
        states = iter((failed, pending))
        adapter._read_assignment = lambda _binding, resolve: next(states)
        adapter._one_uint = lambda *_args, **_kwargs: 10
        adapter._call = lambda target, signature, args, tag, sender=None: (
            _word_uint(1) if (target, signature, args, sender) == (
                self.registry, "retryJury(bytes32)", [case_id], self.sender,
            ) else self.fail("unexpected retry preflight")
        )
        adapter._assert_context_canonical = lambda _context: None
        submitted = []

        def submit(action):
            submitted.append(action)
            return {
                "action_hash": action["action_hash"], "target": action["target"],
                "calldata": action["calldata"], "tx_hash": digest(80),
                "sender": self.sender, "nonce": 7, "state": "submitted",
            }

        adapter._submit = submit
        adapter._inspect_action = lambda _action, _row: {
            "status": "confirmed",
            "assignment_event": {
                "event": "JuryRequested", "roster_version": 10,
                "selection_block": 125, "roster_commitment": digest(92),
            },
        }
        result = adapter.retry_assignment(binding)
        self.assertEqual(result["status"], "pending")
        self.assertEqual(len(submitted), 1)
        self.assertEqual(submitted[0]["action"], "retry_jury")
        self.assertEqual(
            submitted[0]["calldata"],
            chain.encode_contract_call("retryJury(bytes32)", [case_id]),
        )
        self.assertNotEqual(submitted[0]["action"], "finalize_jury")

    def test_retry_assignment_can_confirm_still_unavailable(self) -> None:
        adapter = self.adapter(name="retry-unavailable.sqlite3")
        self.addCleanup(adapter.close)
        case_id = digest(7)
        binding = {
            "schema": "mycomesh.v10.provider-jury-case.v1", "network_id": "fixture",
            "chain_id": 31337, "settlement_contract": self.contract,
            "jury_registry": self.registry, "settlement_key": case_id,
        }
        failed = {
            **binding, "status": "failed", "seed": ZERO_BYTES32,
            "selection_block": 0, "roster_version": 10,
            "block_number": 120, "block_hash": digest(90),
        }
        states = iter((failed, {**failed, "block_number": 123, "block_hash": digest(91)}))
        adapter._read_assignment = lambda _binding, resolve: next(states)
        adapter._one_uint = lambda *_args, **_kwargs: 10
        adapter._call = lambda *_args, **_kwargs: _word_uint(0)
        adapter._assert_context_canonical = lambda _context: None
        submitted = []
        adapter._submit = lambda action: submitted.append(action) or {
            "action_hash": action["action_hash"], "target": action["target"],
            "calldata": action["calldata"], "tx_hash": digest(80),
            "sender": self.sender, "nonce": 7, "state": "submitted",
        }
        adapter._inspect_action = lambda _action, _row: {
            "status": "confirmed",
            "assignment_event": {
                "event": "JuryUnavailable", "roster_version": 10,
                "independent_candidate_count": 2,
            },
        }
        result = adapter.retry_assignment(binding)
        self.assertEqual(result["status"], "failed")
        self.assertEqual(len(submitted), 1)

    def test_retry_assignment_recovers_durable_send_without_rebroadcast(self) -> None:
        adapter = self.adapter(name="retry-recovery.sqlite3")
        self.addCleanup(adapter.close)
        case_id = digest(7)
        binding = {
            "schema": "mycomesh.v10.provider-jury-case.v1", "network_id": "fixture",
            "chain_id": 31337, "settlement_contract": self.contract,
            "jury_registry": self.registry, "settlement_key": case_id,
        }
        failed = {
            **binding, "status": "failed", "seed": ZERO_BYTES32,
            "selection_block": 0, "roster_version": 9,
            "block_number": 120, "block_hash": digest(90),
        }
        action = adapter._retry_action(failed, registry_roster_version=10)
        row = adapter.outbox.reserve(
            action=action, scope=adapter._scope, sender=self.sender, nonce=7,
            target=self.registry, calldata=action["calldata"], gas_price_wei=1,
            gas_units=100_000, raw_tx=self.signed_raw(action, nonce=7),
        )
        adapter.outbox.mark(action["action_hash"], "submitted")
        pending = {
            **binding, "status": "pending", "selection_block": 125,
            "roster_version": 10, "block_number": 123, "block_hash": digest(91),
        }
        states = iter((pending, pending))
        adapter._read_assignment = lambda _binding, resolve: next(states)
        inspected = []
        adapter._inspect_action = lambda observed_action, observed_row: inspected.append(
            (observed_action, observed_row)
        ) or {
            "status": "confirmed",
            "assignment_event": {
                "event": "JuryRequested", "roster_version": 10,
                "selection_block": 125, "roster_commitment": digest(92),
            },
        }
        adapter._submit = lambda _action: self.fail("recovery must not rebroadcast")
        result = adapter.retry_assignment(binding)
        self.assertEqual(result["status"], "pending")
        self.assertEqual(len(inspected), 1)
        self.assertEqual(inspected[0][1]["tx_hash"], row["tx_hash"])

    def test_retry_events_are_bound_to_case_roster_and_receipt(self) -> None:
        adapter = self.adapter(name="retry-events.sqlite3")
        self.addCleanup(adapter.close)
        case_id, tx_hash, block_hash = digest(7), digest(30), digest(31)
        receipt = {
            "transaction_hash": tx_hash, "block_hash": block_hash,
            "block_number": 100,
        }
        action = {
            "settlement_key": case_id, "registry_roster_version": 10,
        }
        common = {
            "address": self.registry, "transactionHash": tx_hash,
            "blockHash": block_hash, "blockNumber": "0x64",
            "logIndex": "0x0", "removed": False,
        }
        requested = {
            **common,
            "topics": [JURY_REQUESTED_TOPIC, case_id, digest(10)],
            "data": "0x" + (_word_uint(125) + _word_hash(digest(40))).hex(),
        }
        event = adapter._retry_event([requested], receipt=receipt, action=action)
        self.assertEqual(event["event"], "JuryRequested")
        self.assertEqual(event["selection_block"], 125)
        # Roster updates can land after the hash-pinned preflight but before
        # mining; monotonic advancement is safe and the refreshed assignment
        # is checked separately.
        advanced = adapter._retry_event(
            [requested], receipt=receipt,
            action={**action, "registry_roster_version": 9},
        )
        self.assertEqual(advanced["roster_version"], 10)

        unavailable = {
            **common,
            "topics": [JURY_UNAVAILABLE_TOPIC, case_id, digest(10)],
            "data": "0x" + _word_uint(2).hex(),
        }
        event = adapter._retry_event([unavailable], receipt=receipt, action=action)
        self.assertEqual(event["event"], "JuryUnavailable")
        self.assertEqual(event["independent_candidate_count"], 2)
        with self.assertRaisesRegex(ProviderJuryChainError, "regressed"):
            adapter._retry_event(
                [unavailable], receipt=receipt,
                action={**action, "registry_roster_version": 11},
            )
        with self.assertRaisesRegex(ProviderJuryChainError, "one retry outcome"):
            adapter._retry_event(
                [requested, unavailable], receipt=receipt, action=action,
            )


if __name__ == "__main__":
    unittest.main()
