stream {
    limit_conn_zone $binary_remote_addr zone=mycomesh_relay_provider_ip:10m;

    server {
        listen 9901 ssl;
        listen [::]:9901 ssl;

        limit_conn mycomesh_relay_provider_ip 4;

        ssl_certificate /etc/letsencrypt/live/mycomesh.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mycomesh.xyz/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_cache shared:MYCOMESH_RELAY_PROVIDER_SSL:10m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;

        proxy_connect_timeout 3s;
        proxy_timeout 1d;
        proxy_pass 127.0.0.1:19901;
    }
}
