import { Buffer } from "node:buffer";
import { describe, expect, it } from "vitest";
import { keccak256, stringToHex } from "viem";
import type { ConsumerV3Authorization } from "./api";
import {
  browserSoftwareConsumerIdentityFromPrivateKeyForTest,
  canonicalBrowserJson,
  signBrowserDocument,
  verifyBrowserDocument,
} from "./browserConsumerIdentity";
import {
  BrowserEnvelopeReplayError,
  BrowserMemoryReplayStore,
  type BrowserTransportKeyBinding,
  browserBase64UrlDecode,
  browserBase64UrlEncode,
  generateBrowserTransportKey,
  openBrowserJsonFrame,
  P2P_SECURE_REQUEST_PURPOSE,
  P2P_SECURE_RESPONSE_PURPOSE,
  sealBrowserJsonFrame,
  verifyBrowserProviderTransportKey,
} from "./browserConsumerTransport";
import {
  type BrowserBoundConsumerV3Plan,
  browserV3AuthorizationMessage,
  browserV3InferenceRequestHash,
  buildBrowserV3InferenceRequest,
} from "./browserConsumerV3";

// Public deterministic inputs generated by the repository's Python protocol implementation.
const now = 1_700_000_000;
const consumer = browserSoftwareConsumerIdentityFromPrivateKeyForTest(
  "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
);
const provider = browserSoftwareConsumerIdentityFromPrivateKeyForTest(
  "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
);

const providerBinding: BrowserTransportKeyBinding = {
  algorithm: "X25519",
  encryption_public_key: "675dd574ed7789310b3d2e7681f3790b466c773b1521fecf36577958371ea52f",
  expires_at: 1_700_086_400,
  identity_public_key: "29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7",
  key_id: "x25519_54cdf328c4d706fab3f3585a3699c4a92325b71dbe1c7ec912d0e79db6a0cf53",
  not_before: now,
  peer_id: "peer_24f6ed6acbfe1009c030d7ca",
  signature: {
    nonce: "11111111111111111111111111111111",
    public_key: "29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7",
    purpose: "mycomesh.transport.key_binding.v1",
    signature: "9d358962215ad224c42214bd27ee931673b7b25ac271a9803c3dae9fbda69cb5629784acac7403f370ec14b8b150b728b1ae201ad529789cbf839b4fab88b804",
    timestamp: now,
  },
  version: "mycomesh-transport-key-v1",
};

const consumerReplyKey = {
  binding: {
    algorithm: "X25519",
    encryption_public_key: "79a631eede1bf9c98f12032cdeadd0e7a079398fc786b88cc846ec89af85a51a",
    expires_at: 1_700_000_600,
    identity_public_key: "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8",
    key_id: "x25519_1bbc33b7b7e0054fa62a1a669c678e933bbdee3801a737cc602e8a83cfa6d356",
    not_before: now,
    peer_id: "peer_56475aa75463474c0285df5d",
    signature: {
      nonce: "22222222222222222222222222222222",
      public_key: "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8",
      purpose: "mycomesh.transport.key_binding.v1",
      signature: "21dde977465013feada4a27054849cf7ff893b6539291e1ae588cc2945b4d8321c3238d8bf3bf324a10dfbbe4e15dc3918723d10e46c23c214651f7c7c972f0e",
      timestamp: now,
    },
    version: "mycomesh-transport-key-v1",
  } satisfies BrowserTransportKeyBinding,
  privateKey: "404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f",
};

const pythonRequestFrameBase64 = "AAAEvHsiYWxnb3JpdGhtIjoiWDI1NTE5LUhLREYtU0hBMjU2LUNIQUNIQTIwUE9MWTEzMDUiLCJjaXBoZXJ0ZXh0IjoiWWtIOEl1WEx3ekNqVnNsSDl1c0lLM0NDX3NkVnJTWkRvbThocWVQUVhPNUJYU3c2R0Vxcnh3IiwiZXBoZW1lcmFsX3B1YmxpY19rZXkiOiI0OTNlODJmYzc0NDY0YTU5MjY4ODE3NjIzZDIwNTNjNWViOGUyY2M0YTk4OGI0ZmVlMTc5ZWM2YjAxMGQ1MzFkIiwiZXhwaXJlc19hdCI6MTcwMDAwMDA2MCwiaXNzdWVkX2F0IjoxNzAwMDAwMDAwLCJtZXNzYWdlX2lkIjoiMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMiLCJub25jZSI6IjQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NCIsInB1cnBvc2UiOiJteWNvbWVzaC5wMnAucmVxdWVzdC52MSIsInJlY2lwaWVudF9rZXlfaWQiOiJ4MjU1MTlfNTRjZGYzMjhjNGQ3MDZmYWIzZjM1ODVhMzY5OWM0YTkyMzI1YjcxZGJlMWM3ZWM5MTJkMGU3OWRiNmEwY2Y1MyIsInJlY2lwaWVudF9wZWVyX2lkIjoicGVlcl8yNGY2ZWQ2YWNiZmUxMDA5YzAzMGQ3Y2EiLCJyZWNpcGllbnRfcHVibGljX2tleSI6IjI5YWNiYWUxNDFiY2NhZjBiMjJlMWE5NGQzNGQwYmM3MzYxZTUyNmQwYmZlMTJjODk3OTRiYzkzMjI5NjZkZDciLCJzZW5kZXJfcGVlcl9pZCI6InBlZXJfNTY0NzVhYTc1NDYzNDc0YzAyODVkZjVkIiwic2VuZGVyX3B1YmxpY19rZXkiOiIwM2ExMDdiZmYzY2UxMGJlMWQ3MGRkMThlNzRiYzA5OTY3ZTRkNjMwOWJhNTBkNWYxZGRjODY2NDEyNTUzMWI4Iiwic2lnbmF0dXJlIjp7ImF1ZGllbmNlIjoiMjlhY2JhZTE0MWJjY2FmMGIyMmUxYTk0ZDM0ZDBiYzczNjFlNTI2ZDBiZmUxMmM4OTc5NGJjOTMyMjk2NmRkNyIsIm5vbmNlIjoiMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMiLCJwdWJsaWNfa2V5IjoiMDNhMTA3YmZmM2NlMTBiZTFkNzBkZDE4ZTc0YmMwOTk2N2U0ZDYzMDliYTUwZDVmMWRkYzg2NjQxMjU1MzFiOCIsInB1cnBvc2UiOiJteWNvbWVzaC50cmFuc3BvcnQuZW52ZWxvcGUudjEiLCJzaWduYXR1cmUiOiJhNDc0OTQ3MGFkMTk3NzM3YmZkMmZhYmY1MDdjNzZhZWNiMGQ0MDUyZjAyMGMxODZmNmQ3MTBhNWY2Y2JmYzFkODAwZmRlOGI4NzQzMjA3YzgzNWYzYmUzMDMwYjMwZGNjMzFiMmRkZmM0MGIyYjBiYWQ2N2JhYzE4NmIzMDgwOCIsInRpbWVzdGFtcCI6MTcwMDAwMDAwMH0sInZlcnNpb24iOiJteWNvbWVzaC1zZWN1cmUtZW52ZWxvcGUtdjEifQ==";
const pythonResponseFrameBase64 = "AAAE23siYWxnb3JpdGhtIjoiWDI1NTE5LUhLREYtU0hBMjU2LUNIQUNIQTIwUE9MWTEzMDUiLCJjaXBoZXJ0ZXh0IjoiS0phc2twaXQzV3dGVi1HS0dtUUk2c2p0NDI5TVpEd1RSR3h5RDFLOVJ1MkdPcEhabjJFYVpSWGdFRE5HQlk1dDZMcTVPWXY2MElzSHVRMWtkVzFBIiwiZXBoZW1lcmFsX3B1YmxpY19rZXkiOiI2MDVhNzI1ZDJhNGFkZmVlYjFhMjllMTdlZGQ2MjFjMWI3NTkzZWU4Y2RiYzQ0YWM2YzRhYjZlMmY4MDVkMjNjIiwiZXhwaXJlc19hdCI6MTcwMDAwMDA2MCwiaXNzdWVkX2F0IjoxNzAwMDAwMDAwLCJtZXNzYWdlX2lkIjoiNTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTUiLCJub25jZSI6IjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NiIsInB1cnBvc2UiOiJteWNvbWVzaC5wMnAucmVzcG9uc2UudjEiLCJyZWNpcGllbnRfa2V5X2lkIjoieDI1NTE5XzFiYmMzM2I3YjdlMDA1NGZhNjJhMWE2NjljNjc4ZTkzM2JiZGVlMzgwMWE3MzdjYzYwMmU4YTgzY2ZhNmQzNTYiLCJyZWNpcGllbnRfcGVlcl9pZCI6InBlZXJfNTY0NzVhYTc1NDYzNDc0YzAyODVkZjVkIiwicmVjaXBpZW50X3B1YmxpY19rZXkiOiIwM2ExMDdiZmYzY2UxMGJlMWQ3MGRkMThlNzRiYzA5OTY3ZTRkNjMwOWJhNTBkNWYxZGRjODY2NDEyNTUzMWI4Iiwic2VuZGVyX3BlZXJfaWQiOiJwZWVyXzI0ZjZlZDZhY2JmZTEwMDljMDMwZDdjYSIsInNlbmRlcl9wdWJsaWNfa2V5IjoiMjlhY2JhZTE0MWJjY2FmMGIyMmUxYTk0ZDM0ZDBiYzczNjFlNTI2ZDBiZmUxMmM4OTc5NGJjOTMyMjk2NmRkNyIsInNpZ25hdHVyZSI6eyJhdWRpZW5jZSI6IjAzYTEwN2JmZjNjZTEwYmUxZDcwZGQxOGU3NGJjMDk5NjdlNGQ2MzA5YmE1MGQ1ZjFkZGM4NjY0MTI1NTMxYjgiLCJub25jZSI6IjU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1IiwicHVibGljX2tleSI6IjI5YWNiYWUxNDFiY2NhZjBiMjJlMWE5NGQzNGQwYmM3MzYxZTUyNmQwYmZlMTJjODk3OTRiYzkzMjI5NjZkZDciLCJwdXJwb3NlIjoibXljb21lc2gudHJhbnNwb3J0LmVudmVsb3BlLnYxIiwic2lnbmF0dXJlIjoiNzNmZjRhNzhmZmE1ZTRlMDAxNWRiOTQ2Yzg4YjA5ZTE0NTI0MTE2NGEyYjYxZDEzMmI0MTlhMmRkZjljODFkNjA2OGNjODBiZjIwNGQxNDkzMmVmMmJlZDhkMDhiYzY1Zjg1NDM1NGU5ZDg0NTc1NGM1Nzk3YTc0YjQ0NjA4MDMiLCJ0aW1lc3RhbXAiOjE3MDAwMDAwMDB9LCJ2ZXJzaW9uIjoibXljb21lc2gtc2VjdXJlLWVudmVsb3BlLXYxIn0=";

function deterministicRandom(...hexValues: string[]) {
  let index = 0;
  return (length: number) => {
    const value = Uint8Array.from(Buffer.from(hexValues[index++] ?? "", "hex"));
    expect(value).toHaveLength(length);
    return value;
  };
}

describe("browser Consumer cross-language identity vectors", () => {
  it("matches Python Ed25519 identity derivation and canonical signatures", () => {
    expect(consumer).toEqual({
      privateKey: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
      publicKey: "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8",
      peerId: "peer_56475aa75463474c0285df5d",
    });
    const signed = signBrowserDocument({ label: "孢子", z: 1 }, consumer, {
      purpose: "vector.identity",
      audience: provider.peerId,
      timestamp: now,
      nonce: "cccccccccccccccccccccccccccccccc",
    });
    expect(canonicalBrowserJson(signed)).toBe(
      "{\"label\":\"孢子\",\"signature\":{\"audience\":\"peer_24f6ed6acbfe1009c030d7ca\",\"nonce\":\"cccccccccccccccccccccccccccccccc\",\"public_key\":\"03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8\",\"purpose\":\"vector.identity\",\"signature\":\"172f52a56bcb9e346652cb5462cf2e71a99b0d3a155d956ca641db030fd4067a2a7bde047658bc02087679ccca324ba85ce7edde18766d6c99e1260ac6177200\",\"timestamp\":1700000000},\"z\":1}",
    );
    expect(verifyBrowserDocument(signed, {
      purpose: "vector.identity",
      audience: provider.peerId,
      now,
    })).toEqual({ label: "孢子", z: 1 });
  });
});

describe("browser Consumer cross-language transport vectors", () => {
  it("uses canonical unpadded base64url for Relay frame bodies", () => {
    expect(browserBase64UrlEncode(Uint8Array.of(0xfb, 0xff, 0))).toBe("-_8A");
    expect(browserBase64UrlDecode("-_8A")).toEqual(Uint8Array.of(0xfb, 0xff, 0));
    expect(() => browserBase64UrlDecode("-_8A=")).toThrow(/without padding/);
    expect(() => browserBase64UrlDecode("AB")).toThrow(/not canonical/);
    expect(() => browserBase64UrlDecode("a+b/")).toThrow(/without padding/);
  });

  it("verifies Python Provider bindings and generates the exact Python reply key", () => {
    expect(verifyBrowserProviderTransportKey(providerBinding, {
      expectedPeerId: provider.peerId,
      expectedIdentityPublicKey: provider.publicKey,
      now,
    })).toMatchObject({
      peerId: provider.peerId,
      identityPublicKey: provider.publicKey,
      keyId: providerBinding.key_id,
    });
    const generated = generateBrowserTransportKey(consumer, {
      lifetimeSeconds: 600,
      now,
      randomBytes: deterministicRandom(
        "404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f",
        "22222222222222222222222222222222",
      ),
    });
    expect(generated).toEqual(consumerReplyKey);
  });

  it("seals the exact Python frame and opens a Python Provider response", () => {
    const frame = sealBrowserJsonFrame({ hello: "孢子", n: 7 }, {
      sender: consumer,
      recipientBinding: providerBinding,
      expectedRecipientPeerId: provider.peerId,
      purpose: P2P_SECURE_REQUEST_PURPOSE,
      ttlSeconds: 60,
      now,
      randomBytes: deterministicRandom(
        "808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f",
        "33333333333333333333333333333333",
        "444444444444444444444444",
      ),
    });
    expect(Buffer.from(frame).toString("base64")).toBe(pythonRequestFrameBase64);

    const replayStore = new BrowserMemoryReplayStore();
    const responseFrame = Uint8Array.from(Buffer.from(pythonResponseFrameBase64, "base64"));
    const opened = openBrowserJsonFrame(responseFrame, {
      recipientKey: consumerReplyKey,
      expectedPurpose: P2P_SECURE_RESPONSE_PURPOSE,
      expectedSenderPeerId: provider.peerId,
      expectedSenderPublicKey: provider.publicKey,
      replayStore,
      now,
    });
    expect(opened.jsonPayload).toEqual({ response: { ok: true, output_text: "向量" } });
    expect(() => openBrowserJsonFrame(responseFrame, {
      recipientKey: consumerReplyKey,
      expectedPurpose: P2P_SECURE_RESPONSE_PURPOSE,
      replayStore,
      now,
    })).toThrow(BrowserEnvelopeReplayError);
  });
});

describe("browser Consumer cross-language Settlement V3 vectors", () => {
  const authorization: ConsumerV3Authorization = {
    authorization_version: "mycomesh.evm.session.v1",
    chain_id: 11_155_111,
    settlement_contract: "0x3333333333333333333333333333333333333333",
    onchain_reservation_id: "0x4444444444444444444444444444444444444444444444444444444444444444",
    consumer_payment_address: "0x5555555555555555555555555555555555555555",
    provider_id: provider.peerId,
    provider_payment_address: "0x6666666666666666666666666666666666666666",
    channel: "codex-standard-v1",
    pricing_hash: "0x7777777777777777777777777777777777777777777777777777777777777777",
    pricing_version: 3,
    request_hash: "0x4fb4525a193f76cb2a41373a1eeb610a4cfdfdc96fbe67e262dab65851c5284d",
    max_fee_units: 123_456,
    expires_at: 1_700_003_600,
    settlement_deadline: 1_700_001_800,
    provider_fallback_allowed: false,
    nonce: "0x8888888888888888888888888888888888888888888888888888888888888888",
    session_public_key: consumer.publicKey,
    wallet_signature: "0x" + "99".repeat(65) as `0x${string}`,
  };
  const unsignedAuthorization = { ...authorization };
  delete unsignedAuthorization.wallet_signature;
  const plan: BrowserBoundConsumerV3Plan = {
    schema: "mycomesh.consumer.v3.plan.v1",
    network_id: "mycomesh-testnet",
    channel_id: "codex",
    backend_policy: "codex-app-server-postvalidated-v1",
    provider_id: provider.peerId,
    provider_payment_address: authorization.provider_payment_address,
    provider_addresses: ["myco+relays://bridge.mycomesh.xyz:443/provider"],
    chain_id: authorization.chain_id,
    settlement_contract: authorization.settlement_contract,
    channel: authorization.channel,
    channel_hash: keccak256(stringToHex("codex-standard-v1")),
    pricing_version: authorization.pricing_version,
    pricing_hash: authorization.pricing_hash,
    request_hash: authorization.request_hash,
    input_size_bytes: 15,
    reserve_input_bytes: 8_000,
    reserve_output_tokens: 64,
    max_fee_units: authorization.max_fee_units,
    expires_at: authorization.expires_at,
    settlement_deadline: authorization.settlement_deadline,
    provider_fallback_allowed: false,
    reservation_salt: "0x" + "cd".repeat(32) as `0x${string}`,
    onchain_reservation_id: authorization.onchain_reservation_id,
    required_confirmations: 1,
    authorization: unsignedAuthorization,
    authorization_message: browserV3AuthorizationMessage(unsignedAuthorization),
  };

  it("matches Python request hashing and both nested Ed25519 signatures", () => {
    expect(browserV3InferenceRequestHash({
      endpoint: "responses",
      model: "model-vector",
      input: "你好 spores",
      maxOutputTokens: 64,
    })).toBe(authorization.request_hash);
    expect(browserV3AuthorizationMessage(authorization)).toBe(
      "{\"authorization_version\":\"mycomesh.evm.session.v1\",\"chain_id\":11155111,\"channel\":\"codex-standard-v1\",\"consumer_payment_address\":\"0x5555555555555555555555555555555555555555\",\"expires_at\":1700003600,\"max_fee_units\":123456,\"nonce\":\"0x8888888888888888888888888888888888888888888888888888888888888888\",\"onchain_reservation_id\":\"0x4444444444444444444444444444444444444444444444444444444444444444\",\"pricing_hash\":\"0x7777777777777777777777777777777777777777777777777777777777777777\",\"pricing_version\":3,\"provider_fallback_allowed\":false,\"provider_id\":\"peer_24f6ed6acbfe1009c030d7ca\",\"provider_payment_address\":\"0x6666666666666666666666666666666666666666\",\"request_hash\":\"0x4fb4525a193f76cb2a41373a1eeb610a4cfdfdc96fbe67e262dab65851c5284d\",\"session_public_key\":\"03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8\",\"settlement_contract\":\"0x3333333333333333333333333333333333333333\",\"settlement_deadline\":1700001800}",
    );
    const built = buildBrowserV3InferenceRequest({
      identity: consumer,
      plan,
      authorization,
      requestId: "request-vector-001",
      endpoint: "responses",
      model: "model-vector",
      input: "你好 spores",
      maxOutputTokens: 64,
      now,
      reservationNonce: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      requestNonce: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    });
    expect((built.paymentReservation.signature as { signature: string }).signature).toBe(
      "cfe629eeaf5eb81ca32eb68190dda5676ea3dc15a00bbf5e88caba104dc3a3bf53a24f602d7abcaeb53d13f18c45f1b9dd6e97fe77aa3849be6aca6a60e35605",
    );
    expect((built.message.signature as { signature: string }).signature).toBe(
      "233ea58c9f089edaaf4571494b535ebca1c2202214c363d279ce963271a8a893170e48cb1d5dfcb9e3ef2feedf3372bb221b580b6050a0e21bdc70fc2023b806",
    );
  });

  it("refuses a plan authorized for a different browser session key", () => {
    expect(() => buildBrowserV3InferenceRequest({
      identity: provider,
      plan,
      authorization,
      requestId: "request-vector-001",
      endpoint: "responses",
      model: "model-vector",
      input: "你好 spores",
      maxOutputTokens: 64,
      now,
      reservationNonce: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      requestNonce: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    })).toThrow(/session_public_key mismatch/);
  });
});
